title: Without Pen and Ink
email: webmaster@withoutpenandink.com
description: > #
  FOO
  BAR
  BAZ
baseurl: ""
url: "http://cout.github.io/"
twitter_username: paulbrannan
github_username: cout
markdown: kramdown
auto: true

theme: jekyll-theme-slate