title: Nonstandard Output
email: cout@rubystuff.org
description: > #
  FOO
  BAR
  BAZ
baseurl: ""
url: "http://cout.github.io/"
twitter_username: paulbrannan
github_username: cout
markdown: kramdown
timezone: EST5EDT
auto: true

theme: jekyll-theme-slate
