local: "en-US"
title: Nonstandard Output
name: Paul Brannan
email: cout@rubystuff.org
logo: "https://avatars2.githubusercontent.com/u/4090"
description: > #
  FOO
  BAR
  BAZ
baseurl: ""
url: "http://cout.github.io/"
twitter:
  username: "paul_brannan"
github_username: cout
markdown: kramdown
timezone: EST5EDT
auto: true
# theme: minimal-mistakes-jekyll
plugins: [ 'jekyll-include-cache' ]
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "contrast"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
comments:
  provider: utterances
paginate: 10
paginate_path: /recent/page:num/
